%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.1.3

-ifndef(login_pb).
-define(login_pb, true).

-define(login_pb_gpb_version, "4.1.3").

-ifndef('SLOGINOUT_PB_H').
-define('SLOGINOUT_PB_H', true).
-record('SLoginOut',
        {code = 0               :: non_neg_integer() | undefined, % = 1, 32 bits
         rtype = 0              :: non_neg_integer() | undefined % = 2, 32 bits
        }).
-endif.

-ifndef('SLOGIN_PB_H').
-define('SLOGIN_PB_H', true).
-record('SLogin',
        {code = 0               :: non_neg_integer() | undefined, % = 1, 32 bits
         userid = <<>>          :: iodata() | undefined, % = 2
         error = 0              :: non_neg_integer() | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('CLOGIN_PB_H').
-define('CLOGIN_PB_H', true).
-record('CLogin',
        {code = 0               :: non_neg_integer() | undefined, % = 1, 32 bits
         phone = <<>>           :: iodata() | undefined, % = 2
         password = <<>>        :: iodata() | undefined, % = 3
         type = 0               :: non_neg_integer() | undefined % = 4, 32 bits
        }).
-endif.

-ifndef('SWXLOGIN_PB_H').
-define('SWXLOGIN_PB_H', true).
-record('SWxLogin',
        {code = 0               :: non_neg_integer() | undefined, % = 1, 32 bits
         userid = <<>>          :: iodata() | undefined, % = 2
         token = <<>>           :: iodata() | undefined, % = 3
         error = 0              :: non_neg_integer() | undefined % = 4, 32 bits
        }).
-endif.

-ifndef('CREGIST_PB_H').
-define('CREGIST_PB_H', true).
-record('CRegist',
        {code = 0               :: non_neg_integer() | undefined, % = 1, 32 bits
         nickname = <<>>        :: iodata() | undefined, % = 2
         phone = <<>>           :: iodata() | undefined, % = 3
         password = <<>>        :: iodata() | undefined, % = 4
         type = 0               :: non_neg_integer() | undefined % = 5, 32 bits
        }).
-endif.

-ifndef('SREGIST_PB_H').
-define('SREGIST_PB_H', true).
-record('SRegist',
        {code = 0               :: non_neg_integer() | undefined, % = 1, 32 bits
         userid = <<>>          :: iodata() | undefined, % = 2
         error = 0              :: non_neg_integer() | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('CWXLOGIN_PB_H').
-define('CWXLOGIN_PB_H', true).
-record('CWxLogin',
        {code = 0               :: non_neg_integer() | undefined, % = 1, 32 bits
         wxcode = <<>>          :: iodata() | undefined, % = 2
         token = <<>>           :: iodata() | undefined, % = 3
         type = 0               :: non_neg_integer() | undefined % = 4, 32 bits
        }).
-endif.

-endif.
