%% -*- coding: utf-8 -*-
%%%-------------------------------------------------------------------
%% @doc packet API, Automatically generated, do not edit
%% Generated by gen_erl.go version 0.1.0
%% Generated time 0.1.0
%% @author piaohua<814004090@qq.com>
%% @end 2018-04-10 19:00:28

%%%-------------------------------------------------------------------

-module(packet).
-author("piaohua").

-export([p/1]).

-include("login_pb.hrl").
-include("game_login_pb.hrl").

%% ------------------------------------------------------------------
%% API Function Definitions
%% ------------------------------------------------------------------

-spec p(Msg) -> {ok, Bin} | {error, undefined} when
      Bin :: binary(),
      Msg :: any().
p(#'SLogin'{} = Msg) ->
	Bin = login_pb:encode_msg(Msg),
	{ok, <<1000:32, Bin/binary>>};
p(#'SRegist'{} = Msg) ->
	Bin = login_pb:encode_msg(Msg),
	{ok, <<1002:32, Bin/binary>>};
p(#'SWxLogin'{} = Msg) ->
	Bin = login_pb:encode_msg(Msg),
	{ok, <<1004:32, Bin/binary>>};
p(#'SLoginOut'{} = Msg) ->
	Bin = login_pb:encode_msg(Msg),
	{ok, <<1006:32, Bin/binary>>};
p(_Msg) ->
	{error, undefined}.
