%% -*- coding: utf-8 -*-
%%%-------------------------------------------------------------------
%% @doc unpack API, Automatically generated, do not edit
%% Generated by gen_erl.go version 0.1.0
%% Generated time 0.1.0
%% @author piaohua<814004090@qq.com>
%% @end 2018-04-10 19:00:28

%%%-------------------------------------------------------------------

-module(unpack).
-author("piaohua").

-export([p/1]).

-include("login_pb.hrl").

%% ------------------------------------------------------------------
%% API Function Definitions
%% ------------------------------------------------------------------

-spec p(Bin) -> {ok, Msg} | {error, undefined} when
      Bin :: binary(),
      Msg :: any().
p(<<Code:32, Bin/binary>>) ->
    p(Code, Bin);
p(_) ->
    {error, undefined}.

p(1000, Bin) ->
	{ok, login_pb:decode_msg(Bin, 'CLogin')};
p(1002, Bin) ->
	{ok, login_pb:decode_msg(Bin, 'CRegist')};
p(1004, Bin) ->
	{ok, login_pb:decode_msg(Bin, 'CWxLogin')};
p(_Code, _Bin) ->
	{error, undefined}.