%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.1.3

-ifndef(game_code_pb).
-define(game_code_pb, true).

-define(game_code_pb_gpb_version, "4.1.3").


-endif.
