%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.1.3

-ifndef(login_pb).
-define(login_pb, true).

-define(login_pb_gpb_version, "4.1.3").

-ifndef('CREGIST_PB_H').
-define('CREGIST_PB_H', true).
-record('CRegist',
        {nickname = <<>>        :: iodata() | undefined, % = 1
         phone = <<>>           :: iodata() | undefined, % = 2
         password = <<>>        :: iodata() | undefined % = 3
        }).
-endif.

-ifndef('SREGIST_PB_H').
-define('SREGIST_PB_H', true).
-record('SRegist',
        {userid = <<>>          :: iodata() | undefined, % = 1
         error = 0              :: non_neg_integer() | undefined % = 2, 32 bits
        }).
-endif.

-endif.
